Branding LPAD-84628f
ElrondNetwork/assets pull request #527
Opened 2022-06-20 20:06 UTC by OverGamesDev

2022-07-12 15:35 UTC, OverGamesDev commented
@AlexandruPislariu we have updated the size of our logo, now it's all good for us

2022-07-13 06:59 UTC, bogdan-rosianu submitted a review, later dismissed

2022-07-13 10:32 UTC, bogdan-rosianu requested changes
Invalid dimensions for PNG! ( 1002x1000 )
Please make it 200x200

2022-07-13 10:33 UTC, OverGamesDev commented
> 

Done

2022-07-13 10:34 UTC, bogdan-rosianu approved these changes

2022-07-13 10:34 UTC, merged